# Generated by Django 3.2.13 on 2022-07-03 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_alter_packageusage_started_at'),
        ('children', '0002_auto_20220625_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='default_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='packages.package'),
        ),
    ]
