# Generated by Django 3.2.13 on 2024-01-13 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20240113_2341'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clockifyintegration',
            unique_together={('project_id', 'integrated_project_id')},
        ),
        migrations.AlterUniqueTogether(
            name='timeentry',
            unique_together={('ref_id', 'ref_name')},
        ),
    ]
