# Generated by Django 3.2.13 on 2024-01-14 15:15

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20240114_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('body', models.TextField(blank=True, null=True)),
                ('headers', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='timeentry',
            options={'verbose_name': 'Time Entry', 'verbose_name_plural': 'Time Entries'},
        ),
    ]
