# Generated by Django 3.2.13 on 2024-01-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_clockifywebhookintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
