# Generated by Django 3.2.13 on 2024-02-02 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0007_alter_project_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='should_convert',
            field=models.BooleanField(default=True),
        ),
    ]
