# Generated by Django 3.2.13 on 2024-02-04 16:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0003_child_default_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225)),
                ('need_verification', models.BooleanField(default=False)),
                ('scheduled_at', models.TimeField(blank=True, null=True)),
                ('children', models.ManyToManyField(to='children.Child')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('todo', 'todo'), ('pending', 'pending'), ('finished', 'finished')], default='todo', max_length=100)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children.child')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children_task.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
