# Generated by Django 3.2.13 on 2024-02-10 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
