# Generated by Django 3.2.13 on 2024-03-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_task', '0005_auto_20240325_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='detail',
            field=models.JSONField(default=dict),
        ),
    ]
