# Generated by Django 3.2.13 on 2024-03-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_task', '0006_alter_task_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tikrar',
            name='version',
            field=models.IntegerField(default=0),
        ),
    ]
