# Generated by Django 3.2.13 on 2024-05-28 03:17

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_task', '0007_alter_tikrar_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='detail',
        ),
        migrations.AddField(
            model_name='task',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]), default=list, size=None),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='task_history/'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='udzur_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('yesno', 'yesno'), ('need_verification', 'need_verification')], default='yesno', max_length=255),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='status',
            field=models.CharField(choices=[('todo', 'todo'), ('pending', 'pending'), ('finished', 'finished'), ('udzur', 'udzur')], default='todo', max_length=100),
        ),
    ]
