# Generated by Django 3.2.13 on 2024-06-03 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children_task', '0008_auto_20240528_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tikraritem',
            name='tikrar',
        ),
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.DeleteModel(
            name='Tikrar',
        ),
        migrations.DeleteModel(
            name='TikrarItem',
        ),
    ]
