# Generated by Django 3.2.13 on 2023-04-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPresenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='migrated_presenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_presenters', to='events.eventpresenter'),
        ),
    ]
