# Generated by Django 3.2.13 on 2023-04-16 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20230416_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='presenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_presenters', to='events.eventpresenter'),
        ),
    ]
