# Generated by Django 3.2.13 on 2024-05-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_presenter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='youtube_link',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='thumbnail',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created',
        ),
        migrations.RemoveField(
            model_name='event',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='event',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='presenter',
        ),
        migrations.RemoveField(
            model_name='event',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='submitter',
        ),
        migrations.RemoveField(
            model_name='event',
            name='zoom_link',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='date_type',
            field=models.CharField(choices=[('hijri', 'hijri'), ('masehi', 'masehi')], default='masehi', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventOrganizer',
        ),
        migrations.DeleteModel(
            name='EventPresenter',
        ),
    ]
