# Generated by Django 3.2.13 on 2022-06-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageusage',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
