# Generated by Django 3.2.13 on 2024-03-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vimflowly', '0002_auto_20240309_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowly',
            name='key',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='flowly',
            unique_together={('key', 'document_id')},
        ),
    ]
