# Generated by Django 3.2.13 on 2025-06-25 15:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address_line1', models.CharField(blank=True, max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('address_line3', models.CharField(blank=True, max_length=255)),
                ('address_line4', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_idr', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='invoice_management.client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'invoice_number')},
            },
        ),
        migrations.CreateModel(
            name='UserClockifyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(help_text='Clockify API Key', max_length=255)),
                ('workspace_id', models.CharField(help_text='Clockify Workspace ID', max_length=255)),
                ('clockify_user_id', models.CharField(help_text='Clockify User ID', max_length=255)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='Hourly rate in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('16258.00'), help_text='IDR per USD exchange rate', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('company_name', models.CharField(default='Muhammad Ihfazhillah', max_length=255)),
                ('company_address_line1', models.CharField(default='MASJID MISYKATUL ATSAR KRADENAN TINGKIR LOR TINGKIR', max_length=255)),
                ('company_address_line2', models.CharField(default='RT 002 RW 006', max_length=255)),
                ('company_address_line3', models.CharField(default='Salatiga Jawa Tengah 50746', max_length=255)),
                ('company_address_line4', models.CharField(default='Indonesia', max_length=255)),
                ('payment_info_line1', models.CharField(default='Wise Account: https://wise.com/share/muhammadi404', max_length=255)),
                ('payment_info_line2', models.CharField(default='or search by email: me@ihfazh.com', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clockify_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Clockify Configuration',
                'verbose_name_plural': 'User Clockify Configurations',
            },
        ),
        migrations.CreateModel(
            name='ManualInvoiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entries', to='invoice_management.invoice')),
            ],
            options={
                'verbose_name': 'Manual Invoice Entry',
                'verbose_name_plural': 'Manual Invoice Entries',
            },
        ),
        migrations.CreateModel(
            name='ClockifyTimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clockify_id', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_hours', models.DecimalField(decimal_places=2, max_digits=10)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='invoice_management.invoice')),
            ],
            options={
                'verbose_name': 'Clockify Time Entry',
                'verbose_name_plural': 'Clockify Time Entries',
                'unique_together': {('invoice', 'clockify_id')},
            },
        ),
    ]
