# Generated by Django 3.2.13 on 2025-06-26 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockifytimeentry',
            name='project_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ClockifyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clockify_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clockify_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clockify Project',
                'verbose_name_plural': 'Clockify Projects',
                'unique_together': {('user', 'clockify_id')},
            },
        ),
    ]
