# Generated by Django 3.2.13 on 2023-08-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicehistory',
            name='value_float',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
