# Generated by Django 3.2.13 on 2023-07-11 20:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_board_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sensors.board')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
