# Generated by Django 3.2.13 on 2022-05-27 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reference_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.bookreference'),
        ),
        migrations.AlterField(
            model_name='book',
            name='reference_text_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='reference_text_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
