# Generated by Django 4.0.4 on 2022-05-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220528_0546'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['page']},
        ),
        migrations.AlterField(
            model_name='page',
            name='page',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
