# Generated by Django 3.2.13 on 2022-11-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_childbookreadinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='childbookreadinghistory',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
