name: Django Deployment


on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: 103.186.0.202
          username: ihfazh
          port: 22
          password: ${{ secrets.PASSWORD }}
          script: bash /home/ihfazh/deploy.sh
          debug: true
